spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: iliass
    password: iliass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true



