eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://auth-db:3306/auth_db
    username: iliass
    password: iliass

  jpa:
    hibernate:
      ddl-auto: update


