services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-ingestion
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: iliass
      MONGO_INITDB_ROOT_PASSWORD: iliass
    networks:
      - movie-recommendation-network
    volumes:
      - mongo-data-ingestion-volume:/data/db
    ports:
      - "27017:27017"
  ingestion-service:
    image: ingestion-service:latest
    container_name: ingestion-service
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
      - discovery-service
    networks:
      - movie-recommendation-network
    ports:
      - "8081:8080"

  preprocessing-service:
    image: preprocessing-service:latest
    container_name: preprocessing-service
    build:
      context: ./preprocessing-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
      - discovery-service
    networks:
      - movie-recommendation-network
    ports:
      - "8082:8000"
    volumes:
      - ./preprocessing-service/data:/app/output
  training-service:
    image: training-service:latest
    container_name: training-service
    build:
      context: ./training-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
       - discovery-service
    networks:
      - movie-recommendation-network
    ports:
      - "8083:8000"
    environment:
      INPUT_CSV: /app/input/ratings_als.csv
      MODEL_PATH: /app/model/als_model
    volumes:
      - ./preprocessing-service/data:/app/input
      - ./training-service/model:/app/model

  recommendation-service:
    build:
      context: ./recommendation-service
      dockerfile: Dockerfile
    container_name: recommendation-service
    restart: unless-stopped
    depends_on:
      - training-service
      - discovery-service
    networks:
      - movie-recommendation-network
    volumes:
      - ./training-service/model:/app/model
    ports:
      - "8084:8000"

  movieBFF-service:
    image: moviebff-service:latest
    container_name: movieBFF-service
    build:
      context: ./MovieBFFService
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-service
    networks:
      - movie-recommendation-network
    ports:
      - "8085:8085"

  discovery-service:
    image: discovery-service:latest
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
        - movie-recommendation-network
    ports:
      - "8761:8761"
  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-service
      - ingestion-service
      - preprocessing-service
      - training-service
      - recommendation-service
      - movieBFF-service
    networks:
      - movie-recommendation-network
    ports:
      - "8888:8888"

networks:
  movie-recommendation-network:
    driver: bridge

volumes:
  mongo-data-ingestion-volume: