services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-ingestion
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: iliass
      MONGO_INITDB_ROOT_PASSWORD: iliass
    networks:
      - movie-recommendation-network
    volumes:
      - mongo-data-ingestion-volume:/data/db
    ports:
      - "27017:27017"
  ingestion-service:
    image: ingestion-service:latest
    container_name: ingestion-service
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    networks:
      - movie-recommendation-network
    ports:
      - "8081:8080"

networks:
  movie-recommendation-network:
    driver: bridge

volumes:
  mongo-data-ingestion-volume:

