version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-ingestion
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: iliass
      MONGO_INITDB_ROOT_PASSWORD: iliass
    ports:
      - "27017:27017"
    networks:
      - movie-recommendation-network
    volumes:
      - mongo-data-ingestion-volume:/data/db

  ingestion-service:
    container_name: ingestion-service
    build:
      context: ./ingestion-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    networks:
      - movie-recommendation-network
    volumes:
      - ./datasets:/datasets  
    depends_on:
      - mongodb

  als-training-service:
    container_name: als-training-service
    build:
      context: ./als-training-service
    restart: unless-stopped
    networks:
      - movie-recommendation-network
    volumes:
      - ./datasets:/datasets  
      - als-model-volume:/model

  recommendation-service:
    container_name: recommendation-service
    build:
      context: ./recommendation-service
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - movie-recommendation-network
    volumes:
      - als-model-volume:/model
    depends_on:
      - als-training-service

networks:
  movie-recommendation-network:
    driver: bridge

volumes:
  mongo-data-ingestion-volume:
  datasets-volume:
  als-model-volume:
