spring:
  application:
    name: ingestion-service

  data:
    mongodb:
      uri: mongodb://iliass:iliass@localhost:27017/ingestiondb?authSource=admin
      database: ingestiondb

  batch:
    job:
      enabled: false

